
classes:
- system.linux.system.repo.mcp.apt_mirantis.maas
- system.maas.region.single
- system.maas.region.boot_sources.maas_ephemeral_v3.bss_xenial
- system.maas.region.boot_sources.maas_ephemeral_v3
- cluster.demo.infra
parameters:
  _param:
    maas_region_port: 5240
    maas_name: ${_param:infra_config_hostname}
    maas_gateway: 192.168.100.1
    maas_region_boot_sources_maas_ephemeral_v3_bs_url: http://${_param:aptly_server_deploy_address}:${_param:aptly_server_http_static_http_port}/${_param:apt_mk_version}/maas-ephemeral-v3/
    linux_system_repo_mcp_maas_url: http://${_param:local_repo_url}/${_param:apt_mk_version}/maas/
    maas_region_main_archive: http://${_param:local_repo_url}/${_param:apt_mk_version}/ubuntu
  postgresql:
    # If you are going to change postgresql data here, please adjust it in mcp-drivetrain-model as well
    server:
      enabled: true
      version: 9.5
      bind:
        address: 127.0.0.1
        port: 5432
        protocol: tcp
      clients:
      - 127.0.0.1
      database:
        maasdb:
          encoding: 'UTF8'
          users:
            - name: 'maas'
              password: ${_param:maas_db_password}
              host: 'localhost'
              createdb: true
              rights: 'all privileges'
  maas:
    region:
      commissioning_scripts:
        00-maas-05-simplify-network-interfaces: /etc/maas/files/commisioning_scripts/00-maas-05-simplify-network-interfaces
      bind:
        host: ${_param:deploy_address}
        port: ${_param:maas_region_port}
      maas_config:
        maas_name: ${_param:maas_name}
      subnets:
        deploy_network:
          name: deploy_network
          cidr: 192.168.100.0/24
          fabric: ${maas:region:fabrics:deploy_fabric:name}
          gateway_ip: ${_param:maas_gateway}
          ipranges:
            1:
              end: 192.168.100.250
              start: 192.168.100.41
              type: dynamic
              subnet: ${maas:region:subnets:deploy_network:name}
      fabrics:
        deploy_fabric:
          name: deploy_fabric
          description: 'Fabric for deploy_network'
          vlans:
            0:
              name: 'vlan 0'
              description: "Deploy VLAN"
              dhcp: True
              # FXIME: after refactoring domain module, it should
              # be fixed to exactly use FQDN, not only hostname
              primary_rack: "${linux:network:hostname}"
    cluster:
      region:
        host: ${_param:deploy_address}
        port: ${_param:maas_region_port}
        saltstack_repo_key: ${_param:aptly_gpg_public_key}
        saltstack_repo_trusty: "http://${_param:local_repo_url}/ubuntu-trusty/salt/${_param:salt_version} ${_param:apt_mk_version} main"
        saltstack_repo_xenial: "http://${_param:local_repo_url}/ubuntu-xenial/salt/${_param:salt_version} ${_param:apt_mk_version} main"
