parameters:
  _param:
    # MAAS
    # Do not change below values as needed for prebuilt day01 image
    maas_admin_username: mirantis
    maas_admin_password: r00tme
    maas_db_password: fRqC7NJrBR0x
    # StackLight
    alerta_admin_password_generated: UJ3GhdQPQiwMYla1
    grafana_password_generated: zjdyZmWhKXUWquon
    mysql_grafana_password_generated: T32fb9WmyYFq5Z8I
    influxdb_stacklight_password_generated: kN15KGf4dMEwndiJ
    influxdb_admin_password_generated: E8aPKTWzjVJZpoSw
    influxdb_password_generated: wYJL8glfuWjLynJQ
    stacklight_log_keepalived_password_generated: 1OiJPIgj8g2NRv5s
    stacklight_telemetry_keepalived_password_generated: Hw6vxbV4xsS4ymtR
    keepalived_stacklight_monitor_vip_password_generated: zdB7I364T2ZYX2JD
    keepalived_prometheus_vip_password_generated: syNxbAVhli9yFUTZ
    stacklight_monitor_rabbitmq_password_generated: hmPrUeQP3vagqoPT
    stacklight_monitor_uchiwa_password_generated: X0cMp2GwRYIaaHyY
    stacklight_monitor_keepalived_password_generated: dlqPB9mlVja941VV
    # OpenStack
    horizon_secret_key_generated: PpeU8C1MAdSaTVKQiIlCs3eEgDWwoeweE1ClcrRkJgkn3AQkhWxc1TH6ptZ3sYks
    keystone_swift_password_generated: 1f4B99Zv7WTCiwBp
    rabbitmq_openstack_password_generated: rrKPLxhSnYtMtS5E
    heat_domain_admin_password_generated: Y2TyDo3YBv1814Db
    ceilometer_influxdb_password_generated: miIgabk4PbkTAqSs
    billometer_secret_key_generated: MYCcW8RkUwYoXTLGx1EDkOLpY5HGVGzl5155PLtwPdVFNHH45flfKLk96QPg1Bss
    mysql_aodh_password_generated: Zo9lvh0K8T8CwYQa
    mysql_cinder_password_generated: boos9F4zly9VCycZ
    mysql_ceilometer_password_generated: DjGuwJMmvbDvdZmN
    mysql_glance_password_generated: hmjeKSF7MMkcyVQO
    mysql_gnocchi_password_generated: xwQ7QS9hrUVNZivr
    mysql_heat_password_generated: VefCv5Jz1alKnrgY
    mysql_keystone_password_generated: 8sEb2BQjBh95Evw5
    mysql_neutron_password_generated: OHQHzOFZIU06EJvG
    mysql_nova_password_generated: 4zAqhI8INFBVGUXB
    mysql_panko_password_generated: AUx5U6sp7wm5NWje
    mysql_designate_password_generated: QynpWUNB0Qg6Y7fI
    keystone_service_token_generated: K0gK0vMY3dbRKTzb
    keystone_admin_password_generated: 5mKCM9L6Kpw9QEYO
    keystone_ceilometer_password_generated: IlQHS2oCwmblzDBx
    keystone_cinder_password_generated: KTSIyh02HAdp6YqN
    keystone_glance_password_generated: BFC4rr6DYw0hNhmZ
    keystone_gnocchi_password_generated: eNo201ELoIpZ8jiY
    keystone_heat_password_generated: UbH6i6mKM1HVTfrN
    keystone_keystone_password_generated: JPueICBOwnpx3hFa
    keystone_neutron_password_generated: WrHIz4py9pPhhwk2
    keystone_nova_password_generated: MzgyeHj5rbxxJ6iV
    keystone_aodh_password_generated: XB5UgMGbj1FMKSYq
    keystone_panko_password_generated: g4qfKD1uRms93YMK
    keystone_designate_password_generated: VkXrlpUkPd1KQH8r
    ceilometer_secret_key_generated: 5M905gYdZp4IolDu
    mongodb_ceilometer_password_generated: O2aHqxqZLYBPOGJT
    mongodb_admin_password_generated: M6DDKUK3Eb15yL5e
    mongodb_shared_key_generated: YkUz7eLz0YxgiibybgynzYjCUpthQNqk5vLq255fj3y6SctUv4mpDbD6fra75WMG
    openstack_metadata_password_generated: zw8VKS7sl55TZdtl
    keystone_billometer_password_generated: sWYLH1wmWbarlj0F
    cinder_storage_secret_uuid_generated: "b7e4ec0f-eda9-1013-45b0-0c2d906b480b"
    nova_storage_secret_uuid_generated: "2d866325-b585-5e8c-5ef4-08c15a5dd57c"
    nova_memcache_secret_key_generated: IWil5dFLSj7lGtzU
    cinder_memcache_secret_key_generated: cWPwF7AOd2Yqf7jw
    glance_memcache_secret_key_generated: s3o2LLWSACQWlnUN
    neutron_memcache_secret_key_generated: EdOcJJMuN2ChxYLe
    heat_memcache_secret_key_generated: IA1Hh9Q14mTHonSI
    # DriveTrain / CICD
    openldap_admin_password_generated: jHCjns7WOouHhyV0
    openldap_config_password_generated: iB9x3f22fJgyKPxV
    openldap_readonly_password_generated: NzW31mtdFk8esz1V
    jenkins_admin_password_generated: PNht8cRVcFaAxzK6
    gerrit_admin_password_generated: BQ1j6hWtwN867oc5
    cicd_keepalived_vip_password_generated: WX366cVg33ClSFJI
    cicd_mysql_admin_password_generated: SQtEeiDq9dd5qLeQ
    cicd_mysql_gerrit_password_generated: xYyFfnMe7HKrdlyM
    jenkins_admin_public_key_generated: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDfLmaoFdj+3T+gegDdmBZdupgsCCB3mN3U3/gf6A9Ghgn+Co+gBCPGW+fHpRKbGA1MRBBWY0BJfY+qUr4rToDjFcvVjRYLBVt0itrbieH9eFWUQMe8hMq4l6leYBc74Sw0FY54d5PXoc4vTS5+9ARnkLAghUuBFhcooCE3fnlMwjmbeDHbgwdq5y/FYCX8lngSBhmWkoJ+LFFT0IpRkkMpFNRwVYxj1sntHovcIu8UVDhkiWaBADcKSYXY283vQLHZxp7UYBczspslAt1cQ22UEc5OaJFnYYrP2/19rt5gLmZbZvhKH6UaSp2ScqrB11MfeNSepb3YolLTMcQYE2s9
    jenkins_admin_private_key_generated: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEA3y5mqBXY/t0/oHoA3ZgWXbqYLAggd5jd1N/4H+gPRoYJ/gqP
      oAQjxlvnx6USmxgNTEQQVmNASX2PqlK+K06A4xXL1Y0WCwVbdIra24nh/XhVlEDH
      vITKuJepXmAXO+EsNBWOeHeT16HOL00ufvQEZ5CwIIVLgRYXKKAhN355TMI5m3gx
      24MHaucvxWAl/JZ4EgYZlpKCfixRU9CKUZJDKRTUcFWMY9bJ7R6L3CLvFFQ4ZIlm
      gQA3CkmF2NvN70Cx2cae1GAXM7KbJQLdXENtlBHOTmiRZ2GKz9v9fa7eYC5mW2b4
      Sh+lGkqdknKqwddTH3jUnqW92KJS0zHEGBNrPQIDAQABAoIBAG2C+UB1J/s3WWdH
      NnGFlUP8sXq5qiTFT+SK2dfeKNC0KOcNC5i7L0rAAiWGrHCKBsxrgZDCNuNYx0wO
      Od5KMRg8s75f8ncJ8+xlzip3p/qWN3f9qYSprEeTs7npcL0jKmuMQFKAan0emmu/
      dZc56YdgCeyLO5dl3YtDt8jhOGge40bhGnDXOWjLWLEdIjAZ2PQFJT1NQ4KJ7keW
      Mz0KuKS0uV3AghCjbV5QBhmEpvOlxvDo7SMgS5+9QxbBKDbhzpcjT761h1rM6Kds
      4gXqFp/p3vmAt7MZLEUN+/fJ2PafDUTkErGWydeDdCjIgIVHCGdCy4oSXgksxOrm
      k0GQ4cECgYEA8pwJqwAbH+WxJyA8HiCM/XYnK6JTEdI7OCSnQ7by0cqRvJLiz91m
      tiW2TJx7Xo3kQTbTRa6632WrFIAykE+rLw8XcEDmx87/TV/s1KSjbh+n5rqreT8F
      Ftd4zzzm/x52/7edGRj6dN4PrwPJvgQiW3YeaYLHjndDPVG3GqJl9mkCgYEA63/Z
      w0NkIQc8Kud8jyZPXY2rDC9scYRdnK7Ml0B56ywgPJuZLA+vKGIexD5f9lsgGWNe
      GTXlQDTcEV9AJt8UDuydEoGp4sJU/WVi5Bd8ncLWqBJZFSJR6wdR1Yp3ZkAbtODB
      vUQkw1i0CFUE6H3lxN62T2464OhQkB5306JiO7UCgYEAvtTaDfXRYC+uPxZt80yr
      Wht8CChwqw3wouLB5tObAEYUiH4JhnOifRgA4xYbPG7j4iAb4y3jtCEmhsOoAjeI
      cUWvrA6A+R3rV5NimIjAPLkNusGOa5qUiDkIwAopsPbnp5FoMvug1hhtwb57C8n4
      tHSey2OhUICjFTKXko23IjECgYABhgo6oSz8qbdR7712j6Dj0g7RPV1OPrT8VoUs
      VVZ0lwx+V+NdzZwsfrYEPwMP7PcAMwxgzWB2UeE6m4smtTrD/fPmMsCOnwM9wHIr
      V5uOybvpynSZFmfBRYLaBtNO7gs/2FRojRBP0zsW8rXdazMZWveC/AuVeOtMg2Xz
      EJHiIQKBgAo5KJgj9GZUqWwY0A0gqLtLePg4nJg8ZGbTctioP/L4f5qKTKxGs/JG
      LX9jSWE6U86u5SgbiNMaun8IdEa0O2K035D9fnMtYSvTN8F30RqHy8lyDLKEgpA1
      tFkctiO6jvkfptOf77OAGeeWRPao9A3R/L8+Tffr1NLYusik6tI+
      -----END RSA PRIVATE KEY-----
    # Ceph
    rgw_keepalived_vip_password_generated: YPc8VQQWQVo
    ceph_cluster_fsid_generated: "1fc1152e-027e-7665-142f-0a967bee7a58"
    rabbitmq_admin_password_generated: gIwIAF8RiYCTgYI5
    rabbitmq_secret_key_generated: hmNwWracODgYH2Ev
    galera_server_maintenance_password_generated: icul5s4AwpRIC1xE
    galera_server_admin_password_generated: DbPGJRzHr1bP1xZv
    docker_registry_http_secret_generated: rzu9CN5ZMThu8Wzf
